# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f06a013f113b3b43fbacc05336d732a8360ff3d882a9de4b172cda2618673b86a8b71194c64dc20defe2eee4d813449ef5db5a6adbe0d08042d4d4bf9af5efb8

test:
  secret_key_base: 2fe62f84d87c6ae31fc0dbc18956b14535c26d34f2bb1e93b3e26b2368cc4e5487d0a050e2202cd616594497cb4cf77ab96db2524ae8db6d2aa410b8c34c65bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
